### ISSUE TITLE
Very nice idea and nice list

### ISSUE THREAD

**Issue by RohovDmytro** [aioue/tinnitus-treatments#1]
Do you have any updates to OPML? How is your tinnitus treatment went?

**Comment by aioue** [comment]
Thank you for your comment.

No updates from me. I am no longer hunting for existing treatment options and now just look at upcoming research and trials occasionally.

If I had the 30,000(!) CHF, I would try the HIFU in Switzerland http://sonimodul.ch. Apart from that, waiting for gene therapy, small molecule therapy, or something new.

**Comment by RohovDmytro** [comment]
@aioue, I've made two attempts to google the connection between HIFU and tinnitus but struggled. It is not a direct cure? Just «one possible option»? Maybe there are some studies or promises for 30,000 CHF? 🥇

**Comment by aioue** [comment]
**There is currently no evidence it is direct, or partial cure.**

Just an idea I would personally try. I am not a doctor or a medical professional. Just a person with tinnitus.

Try https://www.tinnitustalk.com for more up-to-date information.
